# Generated by Django 4.0 on 2021-12-22 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voiture', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Voiture',
        ),
    ]
