# Generated by Django 4.0 on 2021-12-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture', '0002_rename_todo_voiture'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='travail',
            field=models.BooleanField(default=True),
        ),
    ]
