# Generated by Django 4.0 on 2021-12-26 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voiture', '0004_voiture_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiture',
            name='cover',
        ),
    ]
