# Generated by Django 4.0 on 2021-12-27 14:03

from django.db import migrations, models
import voiture.models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture', '0005_remove_voiture_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=voiture.models.upload_path),
        ),
    ]
