# Generated by Django 4.0 on 2021-12-28 19:19

from django.db import migrations, models
import voiture.models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture', '0006_voiture_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='cover',
            field=models.ImageField(default='posts/default.jpg', upload_to=voiture.models.upload_path, verbose_name='Cover'),
        ),
    ]
