# Generated by Django 4.0 on 2021-12-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture', '0007_alter_voiture_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='assurance',
            field=models.DateField(),
        ),
    ]
