# Generated by Django 4.0 on 2021-12-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture', '0008_alter_voiture_assurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='vignette',
            field=models.DateField(),
        ),
    ]
