# Generated by Django 4.0 on 2022-01-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture', '0010_alter_voiture_assurance_alter_voiture_vignette'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='assurance',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='vignette',
            field=models.DateField(),
        ),
    ]
