# Generated by Django 4.0.1 on 2022-01-12 16:40

from django.db import migrations, models
import voiture.models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture', '0011_alter_voiture_assurance_alter_voiture_vignette'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='cover',
            field=models.ImageField(default='posts', upload_to=voiture.models.upload_path, verbose_name='Cover'),
        ),
    ]
